Repository final-gabom/gabom-project, pull requests merged in 2025-08, with the labels that each got.

#206 Refactor: 퀘스트 등록 기능 리펙토링
  src/main/java/com/explorer/gabom/domain/quest/dto/UserQuestDto.java
  src/main/java/com/explorer/gabom/domain/quest/entity/UserQuest.java
  src/main/java/com/explorer/gabom/domain/quest/repository/QuestRepository.java
  src/main/java/com/explorer/gabom/domain/quest/repository/QuestRepositoryCustom.java
  src/main/java/com/explorer/gabom/domain/quest/repository/QuestRepositoryImpl.java
  src/main/java/com/explorer/gabom/domain/quest/repository/UserQuestRepository.java
  src/main/java/com/explorer/gabom/domain/quest/repository/UserQuestRepositoryCustom.java
  src/main/java/com/explorer/gabom/domain/quest/repository/UserQuestRepositoryImpl.java
  src/main/java/com/explorer/gabom/domain/quest/service/AdminQuestServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/service/UserQuestServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/type/ProgressStatus.java
  src/main/java/com/explorer/gabom/domain/quest/util/QuestOrderSpecifierUtil.java
Labels: refactor

#217 Test: 퀘스트 테스트 코드 작성
  build.gradle
  src/test/java/com/explorer/gabom/domain/quest/service/AdminQuestServiceTest.java
  src/test/java/com/explorer/gabom/domain/quest/service/QuestServiceTest.java
  src/test/java/com/explorer/gabom/domain/quest/service/UserQuestServiceTest.java
  src/test/resources/application-test.yml
Labels: test

#211 Test: 칭호 기능 테스트 코드 작성
  src/main/java/com/explorer/gabom/domain/title/dto/response/UserTitleResponse.java
  src/test/java/com/explorer/gabom/domain/title/controller/AdminTitleControllerTest.java
  src/test/java/com/explorer/gabom/domain/title/controller/UserTitleControllerTest.java
  src/test/java/com/explorer/gabom/domain/title/service/TitleServiceTest.java
Labels: test

#237 [Test]#235 Authcontroller 테스트코드 수정
  src/test/java/com/explorer/gabom/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/explorer/gabom/domain/auth/controller/EmailAuthControllerTest.java
  src/test/java/com/explorer/gabom/domain/auth/service/AuthServiceTest.java
  src/test/java/com/explorer/gabom/domain/auth/service/EmailAuthServiceTest.java
  src/test/java/com/explorer/gabom/domain/auth/service/PasswordResetServiceTest.java
  src/test/java/com/explorer/gabom/domain/user/controller/UserBlockControllerTest.java
  src/test/java/com/explorer/gabom/domain/user/controller/UserControllerTest.java
  src/test/java/com/explorer/gabom/domain/user/controller/UserControllerTest_Title.java
  src/test/java/com/explorer/gabom/domain/user/service/UserServiceImplTest.java
  src/test/java/com/explorer/gabom/domain/user/service/UserServiceImplTest_Title.java
Labels: test

#241 Feat: 탐험 장소 Swagger
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceControllerDocs.java
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceRecommendationController.java
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceRecommendationControllerDocs.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceCreateRequest.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceRecommendationRequest.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceRecommendationRequestDto.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceUpdateRequest.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/OffsetDto.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/PlaceCreateResponse.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/PlaceDetailResponseDto.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/PlaceSummary.java
  src/main/java/com/explorer/gabom/domain/place/entity/Place.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceRecommendationService.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceServiceImpl.java
Labels: docs

#226 Fix: Auth 기능 Swagger 설명 보완, 리스폰스에 스키마 추가
  src/main/java/com/explorer/gabom/domain/auth/controller/AuthControllerDocs.java
  src/main/java/com/explorer/gabom/domain/auth/controller/EmailAuthControllerDocs.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/EmailCodeVerifyRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/EmailRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/PasswordResetRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/PasswordResetVerifyRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/response/CheckNicknameResponse.java
  src/main/java/com/explorer/gabom/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/explorer/gabom/domain/auth/dto/response/SignupResponse.java
Labels: docs

#245 [Docs] #240 User Swagger
  src/main/java/com/explorer/gabom/domain/user/controller/UserController.java
  src/main/java/com/explorer/gabom/domain/user/controller/UserControllerDocs.java
  src/main/java/com/explorer/gabom/domain/user/dto/UserDto.java
  src/main/java/com/explorer/gabom/domain/user/dto/UserSummaryDto.java
  src/main/java/com/explorer/gabom/domain/user/dto/request/PasswordUpdateRequest.java
  src/main/java/com/explorer/gabom/domain/user/dto/request/UpdateMainTitleRequest.java
  src/main/java/com/explorer/gabom/domain/user/dto/request/UserUpdateRequest.java
Labels: docs

#232 Docs: activitylog swagger 작성
  src/main/java/com/explorer/gabom/domain/activity/controller/UserActivityLogController.java
  src/main/java/com/explorer/gabom/domain/activity/controller/UserActivityLogControllerDocs.java
  src/main/java/com/explorer/gabom/domain/activity/dto/response/UserActivityLogResponse.java
Labels: docs

#249 Settings: application.yml 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: settings

#267 Feature: #260 UserService쪽 Address관련 메소드 수정
  src/main/java/com/explorer/gabom/domain/address/dto/AddressCodeComponents.java
  src/main/java/com/explorer/gabom/domain/address/dto/AddressDto.java
  src/main/java/com/explorer/gabom/domain/address/dto/request/AddressRequest.java
  src/main/java/com/explorer/gabom/domain/address/dto/response/AddressCreateResponse.java
  src/main/java/com/explorer/gabom/domain/address/entity/Address.java
  src/main/java/com/explorer/gabom/domain/address/entity/Eupmyeondong.java
  src/main/java/com/explorer/gabom/domain/address/entity/Sigungu.java
  src/main/java/com/explorer/gabom/domain/address/repository/AddressRepository.java
  src/main/java/com/explorer/gabom/domain/address/repository/EupmyeondongRepository.java
  src/main/java/com/explorer/gabom/domain/address/service/AddressService.java
  src/main/java/com/explorer/gabom/domain/address/type/AddressType.java
  src/main/java/com/explorer/gabom/domain/user/controller/UserController.java
  src/main/java/com/explorer/gabom/domain/user/controller/UserControllerDocs.java
  src/main/java/com/explorer/gabom/domain/user/dto/UserDto.java
  src/main/java/com/explorer/gabom/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/explorer/gabom/domain/user/entity/User.java
  src/main/java/com/explorer/gabom/domain/user/service/UserService.java
  src/main/java/com/explorer/gabom/domain/user/service/UserServiceImpl.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/test/java/com/explorer/gabom/domain/address/service/AddressServiceTest.java
  src/test/java/com/explorer/gabom/domain/user/controller/UserControllerIntegrationTest.java
  src/test/java/com/explorer/gabom/domain/user/service/UserServiceImplTest.java
  src/test/java/com/explorer/gabom/domain/user/service/UserServiceImplTest_Title.java
Labels: feature, refactor

#281 [Feature] #278 place list 에 주소 필터 추가 및 기본 정렬 조건 설정
  src/main/java/com/explorer/gabom/domain/address/entity/Address.java
  src/main/java/com/explorer/gabom/domain/address/service/AddressService.java
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceControllerDocs.java
  src/main/java/com/explorer/gabom/domain/place/dto/PlaceSummary.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceSearchCond.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceServiceImpl.java
Labels: feature

#289 Feat: 랭킹 계산 및 조회 기능 추가
  build.gradle
  docker-compose.yml
  src/main/java/com/explorer/gabom/GabomApplication.java
  src/main/java/com/explorer/gabom/domain/file/repository/AttachmentFileRepository.java
  src/main/java/com/explorer/gabom/domain/level/entity/Level.java
  src/main/java/com/explorer/gabom/domain/level/repository/LevelRepository.java
  src/main/java/com/explorer/gabom/domain/level/service/LevelService.java
  src/main/java/com/explorer/gabom/domain/quest/service/UserQuestServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/type/QuestConditionType.java
  src/main/java/com/explorer/gabom/domain/ranking/controller/RankingController.java
  src/main/java/com/explorer/gabom/domain/ranking/controller/RankingControllerDocs.java
  src/main/java/com/explorer/gabom/domain/ranking/dto/RankingDto.java
  src/main/java/com/explorer/gabom/domain/ranking/entity/Ranking.java
  src/main/java/com/explorer/gabom/domain/ranking/message/ExpEventConsumer.java
  src/main/java/com/explorer/gabom/domain/ranking/message/ExpEventMessage.java
  src/main/java/com/explorer/gabom/domain/ranking/message/ExpEventProducer.java
  src/main/java/com/explorer/gabom/domain/ranking/repository/RankingRepository.java
  src/main/java/com/explorer/gabom/domain/ranking/service/RankingServiceImpl.java
  src/main/java/com/explorer/gabom/domain/sql/controller/SqlExecutionController.java
  src/main/java/com/explorer/gabom/domain/sql/service/SqlExecutionService.java
  src/main/java/com/explorer/gabom/domain/title/repository/TitleRepository.java
  src/main/java/com/explorer/gabom/domain/user/entity/User.java
  src/main/java/com/explorer/gabom/global/config/RabbitMQConfig.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/data/level.sql
  src/main/resources/data/quest.sql
  src/main/resources/data/title.sql
  src/test/java/com/explorer/gabom/domain/quest/service/UserQuestServiceTest.java
  src/test/resources/application-test.yml
Labels: feature

#279 [Feature]#265 소셜로그인 카카오
  src/main/java/com/explorer/gabom/domain/auth/controller/AuthController.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/explorer/gabom/domain/auth/service/AuthService.java
  src/main/java/com/explorer/gabom/domain/batch/TestAdminSeeder.java
  src/main/java/com/explorer/gabom/domain/social/controller/SocialLoginController.java
  src/main/java/com/explorer/gabom/domain/social/dto/OAuthUserInfo.java
  src/main/java/com/explorer/gabom/domain/social/dto/SsoAuthToken.java
  src/main/java/com/explorer/gabom/domain/social/dto/request/SocialSignupRequest.java
  src/main/java/com/explorer/gabom/domain/social/dto/response/SignupResponse.java
  src/main/java/com/explorer/gabom/domain/social/dto/response/SocialLoginResponse.java
  src/main/java/com/explorer/gabom/domain/social/entity/SocialAccount.java
  src/main/java/com/explorer/gabom/domain/social/repository/SocialAccountRepository.java
  src/main/java/com/explorer/gabom/domain/social/service/KakaoService.java
  src/main/java/com/explorer/gabom/domain/social/service/SocialLoginService.java
  src/main/java/com/explorer/gabom/domain/social/service/SocialLoginServiceFactory.java
  src/main/java/com/explorer/gabom/domain/social/service/SocialService.java
  src/main/java/com/explorer/gabom/domain/social/type/SocialProvider.java
  src/main/java/com/explorer/gabom/domain/user/entity/User.java
  src/main/java/com/explorer/gabom/domain/user/service/UserService.java
  src/main/java/com/explorer/gabom/domain/user/service/UserServiceImpl.java
  src/main/java/com/explorer/gabom/domain/user/type/SocialProvider.java
  src/main/java/com/explorer/gabom/global/config/RestTemplateConfig.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/java/com/explorer/gabom/global/redis/config/RedisConfig.java
  src/main/java/com/explorer/gabom/global/redis/service/RedisTokenService.java
  src/main/java/com/explorer/gabom/global/security/jwt/JwtProvider.java
  src/main/java/com/explorer/gabom/global/security/jwt/JwtTokens.java
  src/main/resources/application-local.yml
Labels: feature

#272 feature/#270 내 장소/글에 인증글 생성 시 알림
  build.gradle
  src/main/java/com/explorer/gabom/domain/exploration/controller/ExplorationController.java
  src/main/java/com/explorer/gabom/domain/exploration/entity/Exploration.java
  src/main/java/com/explorer/gabom/domain/exploration/repository/ExplorationRepository.java
  src/main/java/com/explorer/gabom/domain/exploration/service/ExplorationService.java
  src/main/java/com/explorer/gabom/domain/missionproof/event/MissionProofNotificationListener.java
  src/main/java/com/explorer/gabom/domain/missionproof/service/MissionProofServiceImpl.java
  src/main/java/com/explorer/gabom/domain/notification/controller/NotificationController.java
  src/main/java/com/explorer/gabom/domain/notification/controller/NotificationControllerDocs.java
  src/main/java/com/explorer/gabom/domain/notification/controller/NotificationTestController.java
  src/main/java/com/explorer/gabom/domain/notification/dto/request/SendNotificationRequestDto.java
  src/main/java/com/explorer/gabom/domain/notification/dto/request/SocketNotificationRequest.java
  src/main/java/com/explorer/gabom/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/com/explorer/gabom/domain/notification/entity/Notification.java
  src/main/java/com/explorer/gabom/domain/notification/event/MissionProofCreatedEvent.java
  src/main/java/com/explorer/gabom/domain/notification/event/PointGrantedEvent.java
  src/main/java/com/explorer/gabom/domain/notification/event/QuestCompletedEvent.java
  src/main/java/com/explorer/gabom/domain/notification/listener/MissionProofEventListener.java
  src/main/java/com/explorer/gabom/domain/notification/listener/NotificationEventListener.java
  src/main/java/com/explorer/gabom/domain/notification/repository/NotificationRepository.java
  src/main/java/com/explorer/gabom/domain/notification/service/NotificationService.java
  src/main/java/com/explorer/gabom/domain/notification/type/NotificationRefType.java
  src/main/java/com/explorer/gabom/domain/notification/type/NotificationType.java
  src/main/java/com/explorer/gabom/domain/quest/dto/QuestDto.java
  src/main/java/com/explorer/gabom/domain/quest/entity/Quest.java
  src/main/java/com/explorer/gabom/domain/quest/service/QuestService.java
  src/main/java/com/explorer/gabom/domain/quest/service/QuestServiceImpl.java
  src/main/java/com/explorer/gabom/global/config/SecurityConfig.java
  src/main/java/com/explorer/gabom/global/config/SwaggerConfig.java
  src/main/java/com/explorer/gabom/global/config/WebSocketConfig.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/java/com/explorer/gabom/global/exception/GlobalExceptionHandler.java
  src/main/java/com/explorer/gabom/global/scheduler/ExplorationAlarmBootstrap.java
  src/main/java/com/explorer/gabom/global/scheduler/ExplorationAlarmScheduler.java
  src/main/java/com/explorer/gabom/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/explorer/gabom/global/websocket/NotificationSocketController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/static/notification.html
  src/test/java/com/explorer/gabom/domain/exploration/controller/ExplorationControllerUnitTest.java
  src/test/java/com/explorer/gabom/domain/exploration/service/ExplorationServiceTest.java
Labels: feature

#317 Feature: 랭킹 상세 조회 기능 추가
  src/main/java/com/explorer/gabom/domain/exploration/controller/ExplorationController.java
  src/main/java/com/explorer/gabom/domain/exploration/service/ExplorationService.java
  src/main/java/com/explorer/gabom/domain/level/entity/Level.java
  src/main/java/com/explorer/gabom/domain/level/service/LevelService.java
  src/main/java/com/explorer/gabom/domain/missionproof/service/MissionProofServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/dto/QuestDto.java
  src/main/java/com/explorer/gabom/domain/quest/dto/request/QuestCreateRequest.java
  src/main/java/com/explorer/gabom/domain/quest/dto/request/QuestUpdateRequest.java
  src/main/java/com/explorer/gabom/domain/quest/dto/response/QuestCreateResponse.java
  src/main/java/com/explorer/gabom/domain/quest/dto/response/QuestRewardResponse.java
  src/main/java/com/explorer/gabom/domain/quest/dto/response/QuestUpdateResponse.java
  src/main/java/com/explorer/gabom/domain/quest/entity/Quest.java
  src/main/java/com/explorer/gabom/domain/quest/entity/UserQuest.java
  src/main/java/com/explorer/gabom/domain/quest/service/UserQuestServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/type/QuestConditionType.java
  src/main/java/com/explorer/gabom/domain/ranking/controller/RankingController.java
  src/main/java/com/explorer/gabom/domain/ranking/controller/RankingControllerDocs.java
  src/main/java/com/explorer/gabom/domain/ranking/dto/RankingDto.java
  src/main/java/com/explorer/gabom/domain/ranking/dto/RankingSummaryDto.java
  src/main/java/com/explorer/gabom/domain/ranking/entity/Ranking.java
  src/main/java/com/explorer/gabom/domain/ranking/message/ExpEventConsumer.java
  src/main/java/com/explorer/gabom/domain/ranking/message/ExpEventMessage.java
  src/main/java/com/explorer/gabom/domain/ranking/repository/RankingRepository.java
  src/main/java/com/explorer/gabom/domain/ranking/service/RankingService.java
  src/main/java/com/explorer/gabom/domain/ranking/service/RankingServiceImpl.java
  src/main/java/com/explorer/gabom/domain/user/dto/UserDto.java
  src/main/java/com/explorer/gabom/domain/user/entity/User.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/resources/data/quest.sql
  src/test/java/com/explorer/gabom/domain/quest/service/AdminQuestServiceTest.java
  src/test/java/com/explorer/gabom/domain/quest/service/QuestServiceTest.java
  src/test/java/com/explorer/gabom/domain/quest/service/UserQuestServiceTest.java
  src/test/java/com/explorer/gabom/domain/ranking/service/RankingServiceTest.java
Labels: feature

#321 Refactor: AuthControllerTest.java 수정
  src/test/java/com/explorer/gabom/domain/auth/controller/AuthControllerTest.java
Labels: bug

#343 feat: 루트 경로 허용 및 RootController 생성
  src/main/java/com/explorer/gabom/global/RootController.java
  src/main/java/com/explorer/gabom/global/config/SecurityConfig.java
Labels: feature
