Repository final-gabom/gabom-project, pull requests merged in 2025-07, with the labels that each got.

#73 Feat: 공통 응답 객체 추가
  src/main/java/com/explorer/gabom/global/dto/ApiResponse.java
  src/main/java/com/explorer/gabom/global/exception/CustomException.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/java/com/explorer/gabom/global/exception/GlobalExceptionHandler.java
Labels: feature

#78 feat: 탐험 장소 등록 추가 기능 구현
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceCreateRequest.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/PlaceCreateResponse.java
  src/main/java/com/explorer/gabom/domain/place/entity/Place.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepository.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
  src/main/java/com/explorer/gabom/domain/user/entity/User.java
Labels: feature

#91 Feat: 퀘스트 등록 기능 추가
  src/main/java/com/explorer/gabom/domain/activity/aop/ActivityLogAspect.java
  src/main/java/com/explorer/gabom/domain/activity/entity/AdminActivityLog.java
  src/main/java/com/explorer/gabom/domain/activity/entity/UserActivityLog.java
  src/main/java/com/explorer/gabom/domain/activity/repository/ActivityLogRepository.java
  src/main/java/com/explorer/gabom/domain/activity/repository/AdminActivityLogRepository.java
  src/main/java/com/explorer/gabom/domain/activity/repository/UserActivityLogRepository.java
  src/main/java/com/explorer/gabom/domain/activity/type/ActivityType.java
  src/main/java/com/explorer/gabom/domain/quest/controller/QuestController.java
  src/main/java/com/explorer/gabom/domain/quest/dto/request/QuestCreateRequestDto.java
  src/main/java/com/explorer/gabom/domain/quest/dto/response/QuestCreateResponseDto.java
  src/main/java/com/explorer/gabom/domain/quest/entity/Quest.java
  src/main/java/com/explorer/gabom/domain/quest/repository/QuestRepository.java
  src/main/java/com/explorer/gabom/domain/quest/service/QuestService.java
  src/main/java/com/explorer/gabom/domain/quest/service/QuestServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/type/QuestConditionType.java
  src/main/java/com/explorer/gabom/domain/title/entity/Title.java
  src/main/java/com/explorer/gabom/domain/title/repository/TitleRepository.java
  src/main/java/com/explorer/gabom/global/entity/BaseTimeEntity.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
Labels: feature

#96 fix: 탐험 장소 등록/수정 시 객체 user->userId로 변경
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/dto/request/PlaceCreateRequest.java
  src/main/java/com/explorer/gabom/domain/place/entity/Place.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
Labels: bug

#109 [Feature] 로그인 기능 구현
  src/main/java/com/explorer/gabom/domain/auth/controller/AuthController.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/explorer/gabom/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/explorer/gabom/domain/auth/service/AuthService.java
  src/main/java/com/explorer/gabom/domain/user/repository/UserRepository.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/java/com/explorer/gabom/global/jwt/JwtUtil.java
  src/main/java/com/explorer/gabom/global/validator/PasswordValidator.java
Labels: feature, refactor

#113 feat: 탐험 장소 수정 QueryDSL 사용
  build.gradle
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepository.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
  src/main/java/com/explorer/gabom/global/config/QuerydslConfig.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/test/java/com/explorer/gabom/domain/user/service/UserServiceImplTest.java
Labels: feature

#119 Feat: SpringSecurity 에서 발생한 예외 처리
  src/main/java/com/explorer/gabom/global/config/SecurityConfig.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/java/com/explorer/gabom/global/security/CustomAccessDeniedHandler.java
  src/main/java/com/explorer/gabom/global/security/CustomAuthenticationEntryPoint.java
Labels: feature

#121 Feature: #120 Spring Security 권한 처리를 위해 UserRole enum에 ROLE_ 접두사 추가
  src/main/java/com/explorer/gabom/domain/user/type/UserRole.java
  src/main/java/com/explorer/gabom/global/security/Role.java
  src/main/java/com/explorer/gabom/global/security/userdetails/CustomUserDetails.java
Labels: feature

#135 refactor: SignupRequest.java role 어노테이션 변경
  src/main/java/com/explorer/gabom/domain/auth/dto/request/SignupRequest.java
Labels: bug

#128 [Feature] /#47 닉네임 중복 체크기능 구현
  src/main/java/com/explorer/gabom/domain/auth/controller/AuthController.java
  src/main/java/com/explorer/gabom/domain/auth/dto/response/CheckNicknameResponse.java
  src/main/java/com/explorer/gabom/domain/auth/service/AuthService.java
Labels: feature

#124 feat: 탐험 장소 소프트 딜리트 기능 구현
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/entity/Place.java
  src/main/java/com/explorer/gabom/domain/place/entity/PlaceStatus.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepository.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
Labels: feature

#149 [Feature] # 유저 차단하기 기능 구현
  src/main/java/com/explorer/gabom/domain/user/controller/UserBlockController.java
  src/main/java/com/explorer/gabom/domain/user/dto/response/UserBlockResponse.java
  src/main/java/com/explorer/gabom/domain/user/entity/UserBlock.java
  src/main/java/com/explorer/gabom/domain/user/repository/UserBlockRepository.java
  src/main/java/com/explorer/gabom/domain/user/service/UserBlockService.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
Labels: feature

#151 [Refactor] CustomUserDetails 필드에 User객체 추가
  src/main/java/com/explorer/gabom/global/security/userdetails/CustomUserDetails.java
Labels: refactor

#157 Feat: 유저 활동로그 조회 기능
  src/main/java/com/explorer/gabom/domain/activity/controller/UserActivityLogController.java
  src/main/java/com/explorer/gabom/domain/activity/dto/response/UserActivityLogListResponse.java
  src/main/java/com/explorer/gabom/domain/activity/dto/response/UserActivityLogResponse.java
  src/main/java/com/explorer/gabom/domain/activity/entity/UserActivityLog.java
  src/main/java/com/explorer/gabom/domain/activity/repository/UserActivityLogRepository.java
  src/main/java/com/explorer/gabom/domain/activity/repository/UserActivityLogRepositoryCustom.java
  src/main/java/com/explorer/gabom/domain/activity/repository/UserActivityLogRepositoryCustomImpl.java
  src/main/java/com/explorer/gabom/domain/activity/service/UserActivityLogService.java
  src/main/java/com/explorer/gabom/domain/activity/type/ActivityType.java
Labels: feature

#160 [Feature] #50 이메일 인증코드 전송 기능
  build.gradle
  src/main/java/com/explorer/gabom/domain/auth/controller/EmailAuthController.java
  src/main/java/com/explorer/gabom/domain/auth/dto/request/EmailRequest.java
  src/main/java/com/explorer/gabom/domain/auth/service/EmailAuthService.java
  src/main/java/com/explorer/gabom/domain/auth/service/EmailCodeStorage.java
  src/main/java/com/explorer/gabom/global/config/JavaMailSenderConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/java/com/explorer/gabom/domain/user/service/UserServiceImplTest.java
Labels: feature

#171 feat: 탐험 시작 기능 구현
  src/main/java/com/explorer/gabom/domain/Exploration/controller/ExplorationController.java
  src/main/java/com/explorer/gabom/domain/Exploration/dto/request/ExplorationStartRequest.java
  src/main/java/com/explorer/gabom/domain/Exploration/dto/response/ExplorationStartResponse.java
  src/main/java/com/explorer/gabom/domain/Exploration/entity/Exploration.java
  src/main/java/com/explorer/gabom/domain/Exploration/repository/ExplorationRepository.java
  src/main/java/com/explorer/gabom/domain/Exploration/service/ExplorationService.java
  src/main/java/com/explorer/gabom/domain/Exploration/vo/RewardCalculator.java
  src/main/java/com/explorer/gabom/domain/Exploration/vo/RewardRange.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
  src/main/java/com/explorer/gabom/global/util/DistanceCalculator.java
Labels: feature

#172 [Feature] #41 장소 리스트 조회 기능 추가 Place List
  src/main/java/com/explorer/gabom/domain/file/dto/ThumbnailDto.java
  src/main/java/com/explorer/gabom/domain/place/controller/PlaceController.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/OffsetDto.java
  src/main/java/com/explorer/gabom/domain/place/dto/response/PlaceSummary.java
  src/main/java/com/explorer/gabom/domain/place/mapper/PlaceSummaryMapper.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/explorer/gabom/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceService.java
  src/main/java/com/explorer/gabom/domain/place/service/PlaceServiceImpl.java
  src/main/resources/application-local.yml
Labels: feature

#178 feat: 탐험 중인 장소 조회 기능 구현
  src/main/java/com/explorer/gabom/domain/exploration/controller/ExplorationController.java
  src/main/java/com/explorer/gabom/domain/exploration/dto/request/ExplorationStartRequest.java
  src/main/java/com/explorer/gabom/domain/exploration/dto/response/ExplorationCurrentResponse.java
  src/main/java/com/explorer/gabom/domain/exploration/dto/response/ExplorationStartResponse.java
  src/main/java/com/explorer/gabom/domain/exploration/entity/Exploration.java
  src/main/java/com/explorer/gabom/domain/exploration/repository/ExplorationRepository.java
  src/main/java/com/explorer/gabom/domain/exploration/service/ExplorationService.java
  src/main/java/com/explorer/gabom/domain/exploration/vo/RewardCalculator.java
  src/main/java/com/explorer/gabom/domain/exploration/vo/RewardRange.java
  src/main/java/com/explorer/gabom/global/exception/ErrorCode.java
Labels: feature

#180 Fix: 퀘스트 CUD 시 유저-퀘스트도 CUD 적용
  src/main/java/com/explorer/gabom/domain/quest/controller/AdminQuestController.java
  src/main/java/com/explorer/gabom/domain/quest/entity/UserQuest.java
  src/main/java/com/explorer/gabom/domain/quest/repository/UserQuestRepository.java
  src/main/java/com/explorer/gabom/domain/quest/service/AdminQuestServiceImpl.java
  src/main/java/com/explorer/gabom/domain/quest/service/UserQuestServiceImpl.java
Labels: refactor

#188 [Refactor]#186 userServiceImp, authSevice 수정
  src/main/java/com/explorer/gabom/domain/auth/service/AuthService.java
  src/main/java/com/explorer/gabom/domain/auth/service/EmailAuthService.java
  src/main/java/com/explorer/gabom/domain/user/controller/UserController.java
  src/main/java/com/explorer/gabom/domain/user/service/UserService.java
  src/main/java/com/explorer/gabom/domain/user/service/UserServiceImpl.java
Labels: refactor

#190 Feature/187 미션 인증글 상세 조회
  src/main/java/com/explorer/gabom/domain/file/repository/AttachmentFileRepository.java
  src/main/java/com/explorer/gabom/domain/missionproof/controller/MissionProofController.java
  src/main/java/com/explorer/gabom/domain/missionproof/dto/response/MissionProofDetailResponse.java
  src/main/java/com/explorer/gabom/domain/missionproof/service/MissionProofService.java
  src/main/java/com/explorer/gabom/domain/missionproof/service/MissionProofServiceImpl.java
Labels: feature
